from __future__ import annotations

try:
    from enum import StrEnum
except ImportError:
    from enum import Enum
    class StrEnum(str, Enum): pass
class RiskRefusalReason(StrEnum):
    DENY_BY_DEFAULT = "DENY_BY_DEFAULT"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    WALLET_BLOCKED = "WALLET_BLOCKED"
    SCORE_MISSING = "SCORE_MISSING"
    CONFIDENCE_TOO_LOW = "CONFIDENCE_TOO_LOW"
    MODE_FORBIDDEN = "MODE_FORBIDDEN"
    EXECUTION_DISABLED = "EXECUTION_DISABLED"
    TESTNET_CONFIRMATION_REQUIRED = "TESTNET_CONFIRMATION_REQUIRED"
    MAINNET_FORBIDDEN = "MAINNET_FORBIDDEN"
    WALLET_SCORE_NOT_SCORED = "WALLET_SCORE_NOT_SCORED"
    WALLET_SCORE_SAMPLE_LOW = "WALLET_SCORE_SAMPLE_LOW"
    WALLET_SCORE_CONFIDENCE_LOW = "WALLET_SCORE_CONFIDENCE_LOW"
    WALLET_SCORE_PROFIT_FACTOR_MISSING = "WALLET_SCORE_PROFIT_FACTOR_MISSING"
    WALLET_SCORE_NET_PNL_MISSING = "WALLET_SCORE_NET_PNL_MISSING"
    WALLET_SCORE_RISK_TOO_HIGH = "WALLET_SCORE_RISK_TOO_HIGH"
    RESEARCH_OBSERVATION_ONLY = "RESEARCH_OBSERVATION_ONLY"
    PAPER_TRADING_DISABLED = "PAPER_TRADING_DISABLED"
    PAPER_WALLET_SCORE_MISSING = "PAPER_WALLET_SCORE_MISSING"
    PAPER_WALLET_SCORE_NOT_SCORED = "PAPER_WALLET_SCORE_NOT_SCORED"
    PAPER_CONFIDENCE_TOO_LOW = "PAPER_CONFIDENCE_TOO_LOW"
    PAPER_SAMPLE_QUALITY_TOO_LOW = "PAPER_SAMPLE_QUALITY_TOO_LOW"
    PAPER_NOTIONAL_TOO_HIGH = "PAPER_NOTIONAL_TOO_HIGH"
    PAPER_MAX_OPEN_TRADES_REACHED = "PAPER_MAX_OPEN_TRADES_REACHED"
    PAPER_INVALID_SIDE = "PAPER_INVALID_SIDE"
    PAPER_INVALID_PRICE = "PAPER_INVALID_PRICE"
    PAPER_INVALID_NOTIONAL = "PAPER_INVALID_NOTIONAL"
    PAPER_SIMULATION_ONLY = "PAPER_SIMULATION_ONLY"
