from __future__ import annotations

HYPERSMART_INFO_TIME_RANGE_PAGE_LIMIT = 500
HYPERSMART_USER_FILLS_RECENT_LIMIT = 2000
# Conservative guard only. Do not rely on this for long loops: always use
# timestamp cursors, max_pages, max_fills and stopped_reason.
HYPERSMART_USER_FILLS_BY_TIME_MAX_RECENT = 10_000
HYPERSMART_MAX_PAGES_PER_WALLET = 3
HYPERSMART_MAX_FILLS_PER_RUN = 1_500
HYPERSMART_WS_MAX_CONNECTIONS = 10
HYPERSMART_WS_MAX_NEW_CONNECTIONS_PER_MIN = 30
HYPERSMART_WS_MAX_SUBSCRIPTIONS = 1000
HYPERSMART_WS_MAX_UNIQUE_USERS = 10
HYPERSMART_EXPLORER_WEIGHT = 40
HYPERSMART_REST_WEIGHT_PER_MIN_PER_IP = 1200


__all__ = [
    "HYPERSMART_EXPLORER_WEIGHT",
    "HYPERSMART_INFO_TIME_RANGE_PAGE_LIMIT",
    "HYPERSMART_MAX_FILLS_PER_RUN",
    "HYPERSMART_MAX_PAGES_PER_WALLET",
    "HYPERSMART_REST_WEIGHT_PER_MIN_PER_IP",
    "HYPERSMART_USER_FILLS_BY_TIME_MAX_RECENT",
    "HYPERSMART_USER_FILLS_RECENT_LIMIT",
    "HYPERSMART_WS_MAX_CONNECTIONS",
    "HYPERSMART_WS_MAX_NEW_CONNECTIONS_PER_MIN",
    "HYPERSMART_WS_MAX_SUBSCRIPTIONS",
    "HYPERSMART_WS_MAX_UNIQUE_USERS",
]
